Use Azure storage  Terraform state instead local

diff --git a/.github/workflows/mlops-pipeline.yaml b/.github/workflows/mlops-pipeline.yaml
--- a/.github/workflows/mlops-pipeline.yaml
+++ b/.github/workflows/mlops-pipeline.yaml
@@ -208,29 +208,29 @@ jobs:
 
       - name: Terraform Init
         working-directory: terraform
-        #env:
-          #TF_STATE_RESOURCE_GROUP: ${{ secrets.TF_STATE_RESOURCE_GROUP }}
-          #TF_STATE_STORAGE_ACCOUNT: ${{ secrets.TF_STATE_STORAGE_ACCOUNT }}
-          #TF_STATE_CONTAINER: ${{ secrets.TF_STATE_CONTAINER }}
-          #TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
-        #run: |
-        #  echo "Validating backend variables..."
+        env:
+          TF_STATE_RESOURCE_GROUP: ${{ secrets.TF_STATE_RESOURCE_GROUP }}
+          TF_STATE_STORAGE_ACCOUNT: ${{ secrets.TF_STATE_STORAGE_ACCOUNT }}
+          TF_STATE_CONTAINER: ${{ secrets.TF_STATE_CONTAINER }}
+          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
+        run: |
+          echo "Validating backend variables..."
 
-          #test -n "$TF_STATE_RESOURCE_GROUP" || (echo "Missing TF_STATE_RESOURCE_GROUP" && exit 1)
-          #test -n "$TF_STATE_STORAGE_ACCOUNT" || (echo "Missing TF_STATE_STORAGE_ACCOUNT" && exit 1)
-          #test -n "$TF_STATE_CONTAINER" || (echo "Missing TF_STATE_CONTAINER" && exit 1)
-          #test -n "$TF_STATE_KEY" || (echo "Missing TF_STATE_KEY" && exit 1)
+          test -n "$TF_STATE_RESOURCE_GROUP" || (echo "Missing TF_STATE_RESOURCE_GROUP" && exit 1)
+          test -n "$TF_STATE_STORAGE_ACCOUNT" || (echo "Missing TF_STATE_STORAGE_ACCOUNT" && exit 1)
+          test -n "$TF_STATE_CONTAINER" || (echo "Missing TF_STATE_CONTAINER" && exit 1)
+          test -n "$TF_STATE_KEY" || (echo "Missing TF_STATE_KEY" && exit 1)
 
-          #terraform init \
-            #-backend-config="resource_group_name=$TF_STATE_RESOURCE_GROUP" \
-            #-backend-config="storage_account_name=$TF_STATE_STORAGE_ACCOUNT" \
-            #-backend-config="container_name=$TF_STATE_CONTAINER" \
-            #-backend-config="key=$TF_STATE_KEY" \
-            #-backend-config="use_azuread_auth=true" \
-            #-backend-config="use_oidc=true" \
-            #-backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
-            #-backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
-            #-reconfigure
+          terraform init \
+            -backend-config="resource_group_name=$TF_STATE_RESOURCE_GROUP" \
+            -backend-config="storage_account_name=$TF_STATE_STORAGE_ACCOUNT" \
+            -backend-config="container_name=$TF_STATE_CONTAINER" \
+            -backend-config="key=$TF_STATE_KEY" \
+            -backend-config="use_azuread_auth=true" \
+            -backend-config="use_oidc=true" \
+            -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
+            -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
+            -reconfigure
 
       - name: Terraform Validate
         working-directory: terraform
